# Generated by Django 2.2.2 on 2019-06-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('photo_slug', models.CharField(max_length=100)),
            ],
        ),
    ]
