# Generated by Django 2.2.2 on 2019-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='alt_text',
            field=models.CharField(default='Instagram Photo', max_length=100),
        ),
    ]
