# Generated by Django 2.2.2 on 2019-06-21 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ig_photos', '0002_photos_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
